### ISSUE TITLE
Great idea for the skin

### ISSUE THREAD

**Issue by ghost** [Tain101/Deluge-Rainmeter-Skin#1]
Just wanted to say thanks for working on this. It'll go great with my HTPC/seedbox once you're ready to release. If you need someone for bugtesting just let me know!

**Comment by presentday-presenttime** [comment]
The current version should work fine with seedboxes. 

Deluge has an issue with verbose logging right now, so I've half been waiting for that to be updated before I work on the individual side of things.

Feel free to leave any issues/suggestions here.

Any .rmskin files in the repo should be stable.
