### ISSUE TITLE
Torrent speed, number of digits

### ISSUE THREAD

**Issue by maxdd** [Tain101/Deluge-Rainmeter-Skin#7]
Hello Tain,
how is the development going?
I noticed that when i pass for example from 760KiB/s to 1.2MiB/s the value is written as 01.2MiB/s
Not a major issue but surely to be fixed.

**Comment by presentday-presenttime** [comment]
It adds the leading zero to ensure the string is always the same length. Otherwise the skin would potentially be adjusting size every time it updated.

I am still making progress with the next version of the skin, unfortunately I do not have very much free time so things will be slow.

**Comment by maxdd** [comment]
Can you highlight me where that line is? i would like to test it since i've changed a bit the theme.

**Comment by maxdd** [comment]
Moreover can you change the Upload/Download speed to a [Measure] rather than a [Meter]?
In this way we can use the [Measure] to create a LineGraph.

**Comment by presentday-presenttime** [comment]
the formatting is in Deluge.Lua
https://github.com/Tain101/Deluge-Rainmeter-Skin/blob/master/Deluge.lua

Line 11 is the declaration, it is called on line 179
